#!/usr/bin/python

import sys
import os
import numpy

path=os.path.abspath('../')
sys.path.insert(0,path)

from gr_io import *

argvs=sys.argv
if len(set(['-i','-o','-n'])&set(argvs)) != 3:
    raise Exception('parameter lost: -i -o -n')
idx1=argvs.index('-i')+1
idx2=argvs.index('-o')+1
n=argvs.index('-n')+1

G=read_edgelist(argvs[idx1])
n=int(n)

if n >= G.order():
    print 'Network order is %s'%G.order()
    raise Exception('-n is too big.')

index=numpy.random.random_integers(0,G.order()-1,15)
terminals=[G.nodes()[x] for x in index]

termfile=open(argvs[idx2],'w')
for item in terminals:
    termfile.write('%s\n'%item)
termfile.close()    

print 'done'
